### ISSUE TITLE
Unreadable error when error highlight overlaps unknown symbol highlight

### ISSUE THREAD

**Issue by ivanbartsov** [arcticicestudio/nord-jetbrains#101]
Version: 0.8.1

Looks related to #60 (resolved in #62)

Known symbol:
![Screenshot 2019-09-20 at 12 01 20](https://user-images.githubusercontent.com/1104527/65300643-6659fd00-db9e-11e9-9db6-6df6e9420552.png)
Unknown symbol (messed up the class name by deleting last two characters):
![Screenshot 2019-09-20 at 11 53 54](https://user-images.githubusercontent.com/1104527/65300581-2135cb00-db9e-11e9-96ae-767c220b2f96.png)

Unknown, partly selected so background overridden by selection background
![Screenshot 2019-09-20 at 11 54 07](https://user-images.githubusercontent.com/1104527/65300588-272bac00-db9e-11e9-9f01-9b265cf42ca8.png)

In theme settings I can see `background` value for Error is the same as `foreground` for Unknown symbol which doesn't set it's own background, hence the red-on-red issue.

![Screenshot 2019-09-20 at 12 04 09](https://user-images.githubusercontent.com/1104527/65300793-e84a2600-db9e-11e9-801c-2c472d1d2232.png)
![Screenshot 2019-09-20 at 12 04 22](https://user-images.githubusercontent.com/1104527/65300800-eaac8000-db9e-11e9-909e-254828f5cbea.png)

**Comment by ivanbartsov** [comment]
My bad, had an old version of nord 0.4.0 syntax-only plugin installed (alongside the 0.8.1 theme/syntax) that carried the outdated scheme, sorry for false alarm, closing

**Comment by arcticicestudio** [comment]
No problem, glad to see it works for you now 😄 
Unfortunately this is a side-effect because the internal ID of the plugin between version 0.4.0 and 0.5.0 which required to manually uninstall the plugin and re-install if from the marketplace again.
