### ISSUE TITLE
Project window target directory is hard to see

### ISSUE THREAD

**Issue by ld000** [arcticicestudio/nord-jetbrains#105]
In java project, project window target directory is too gray and hard to see.

![image](https://user-images.githubusercontent.com/10431666/67280354-8feca800-f4ff-11e9-9652-b656a9095299.png)

**Comment by arcticicestudio** [comment]
Duplicates #67

---

Hi @ld000 :wave:, thanks for your contribution :+1:
This is the same problem described in #67, [please see my comment][c] and the follow-up conversation that provides information about the problem and **how to solve it on your side**.

As a theme author there is actually no way to fix this using the IDE's scheme API and it might need to be resolved by JetBrains. There is an idea how this could be fixed posed by a user in https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-526185576, but it still need to be evaluated and tested.

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/67#issuecomment-511395276
