### ISSUE TITLE
[Suggestion] Remove italic from braces in RegExp

### ISSUE THREAD

**Issue by n1kk** [arcticicestudio/nord-jetbrains#107]
Is there a reason why RegExp braces `[]{}` are italic? 

I think regular style makes it more readable.
![image](https://user-images.githubusercontent.com/5442968/68661446-3f370080-053b-11ea-872a-af6c565b1ec3.png)
![image](https://user-images.githubusercontent.com/5442968/68661904-09dee280-053c-11ea-847a-5a89cba6b7be.png)

**Comment by arcticicestudio** [comment]
Hi @n1kk :wave:, thanks for your contribution :+1:
That's not the way it should be, I guess something went wrong during the transition from the old to the new theme API.
This can be included in the next release version, feel free to submit a PR if you like :smile:
