### ISSUE TITLE
Go syntax highlighting support for IntelliJ/Goland 2019.3

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-jetbrains#108]
Related to #69, #70

---

Like already documented and fixed in #70, IntelliJ/Goland version 2019.3 also [changes in Go's syntax highlight for the default bundled color schemes][goland].
This again requires to explicitly define the values for some attributes in order to achieve the same highlight like in previous versions that are matching Nord's style guidelines.

[goland]: https://www.jetbrains.com/go/whatsnew/#v2019-3-code-editing

**Comment by Modificator** [comment]
reinstall plugin, it's work well

**Comment by arcticicestudio** [comment]
Yeah, but that's only a workaround. I've submitted #109 instead to ensure it works out-of-the-box after an IDE version update.
