### ISSUE TITLE
Editor Font Not Found Android Studio

### ISSUE THREAD

**Issue by OnurSevket** [arcticicestudio/nord-jetbrains#110]
Hi,

I attached the picture,Nord font not found,Can you help me about changing editor font?

Best Regards

![image](https://user-images.githubusercontent.com/23638184/70654879-40596b80-1c68-11ea-8c09-d2bb0910366e.png)

**Comment by arcticicestudio** [comment]
Hi @OnurSevket, as of [version 0.8.0][0.8.0] the editor theme doesn't include a configuration for the font anymore, see #84 for all details about this decision.
To use the same font like in previous versions, you can simply install the [Source Code Pro][scp] into your system. Restart Android Studio and the font should be available from the drop-down afterwards. You can use any other font for sure, _Source Code Pro_ is just the font family that was configured before #85 was merged.

[0.8.0]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.0
[scp]: https://github.com/adobe-fonts/source-code-pro
