### ISSUE TITLE
Unreadable excluded files

### ISSUE THREAD

**Issue by mistic100** [arcticicestudio/nord-jetbrains#112]
When excluding folders (node_modules for instance) the files list is unreadable.

![Capture d’écran du 2019-12-27 13-56-05](https://user-images.githubusercontent.com/41597/71517988-da4c2580-28b0-11ea-909b-b989f8656de2.png)

**Comment by arcticicestudio** [comment]
Duplicates #57 and #67

---

Hi @mistic100 :wave:, thanks for your contribution :+1:
This is the same problem described in #67, [please see my comment][c] and the follow-up conversation that provides information about the problem and **how to solve it on your side**.

As a theme author there is actually no way to fix this using the IDE's scheme API and it might need to be resolved by JetBrains. There is an idea how this could be fixed posed by a user in https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-526185576, but it still need to be evaluated and tested.

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/67#issuecomment-511395276
