### ISSUE TITLE
Nord Plugin Not Found Appearance & Behavior Theme

### ISSUE THREAD

**Issue by OnurSevket** [arcticicestudio/nord-jetbrains#113]
Hi,

I attached a screenshot on a plugin,Nord Theme showing only coding area,Can you help me ?

![image](https://user-images.githubusercontent.com/23638184/71959303-7ce69b80-3203-11ea-8706-8a49f0fb8e50.png)

**Comment by OnurSevket** [comment]
Intelij Idea About Version

IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by arcticicestudio** [comment]
Hi @OnurSevket, UI themes are only available starting from [IDE versions 2019.1 and higher][b]. If you _Ultimate Edition_ license is still active you should be able to simply upgrade o the latest version.

[b]: https://blog.jetbrains.com/idea/2019/03/intellij-idea-2019-1-is-released-theme-customization-java-12-switch-expressions-debug-inside-docker-containers-and-more/
