### ISSUE TITLE
Unadapted colors in file tree.

### ISSUE THREAD

**Issue by bytecho** [arcticicestudio/nord-jetbrains#114]
I opened a kotlin project [Fuel:](https://github.com/kittinunf/fuel).
Paths like ".gradle/*","*/build/*", "Fuel/build/out/*" have  not been adopted nord color system.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/16740582/72679521-ea8ba500-3aea-11ea-9f22-9bd896e835f2.png">

**Comment by arcticicestudio** [comment]
Duplicates #57 and #67

---

Hi @bytecho :wave:, thanks for your contribution :+1:
This is the same problem described in #67, [please see my comment][c] and the follow-up conversation that provides information about the problem and **how to solve it on your side**.

As a theme author there is actually no way to fix this using the IDE's scheme API and it might need to be resolved by JetBrains. There is an idea how this could be fixed posed by a user in https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-526185576, but it still need to be evaluated and tested.

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/67#issuecomment-511395276

**Comment by bytecho** [comment]
@arcticicestudio  Thanks for response. It's solved follow your suggest.I think it's actually a problem of Idea's api.
