### ISSUE TITLE
Random editor scheme highlight breakage

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-jetbrains#120]
This is a meta-issue to collect and aggregate all information regarding the problems related to “randomly breaking syntax highlighting“. There is an continuously increasing amount of issues related this bug were the root cause is still a mystery.

Related to #69, #70, #77, #78, #108, #109, #115, #117, #119

The following timeline shows the problem based on reported issues in this repository.

### 2019-07-31 — First breakages of Go & JavaScript syntax since IDE versions 2019.2.x

The first cases are documented in #69 & #77 where the syntax highlighting of some Go & JavaScript elements were wrong after updating to IntelliJ version _2019.2.0_, the update that [introduced support for 20+ languages][rl-2019-2] out-of-the-box by integrating [TextMate][tm] schemes.

It resulted in a change for some Go & JavaScript editor color scheme keys that previously inherited the best matching global keys, but used the attributes defined by the parent theme _Darcula_ after the update instead. Therefore Nord's highlighting for Go & JavaScript broke and required to explicitly define the values for the some attributes (merged in #70 & #78) in order to achieve the same highlight like in previous versions:

A [comparison of the changes between Nord plugin version 0.6.0 and 0.7.0][comp-time-v0.6.0-v0.7.0] shows that there were absolutely no changes to the editor color scheme related to the highlighting of Go & JavaScript code. To this time the guess was that the root cause was the integration of _TextMate_ themes and the “fixes“ have been released in [version 0.8.0][rl-v0.8.0].

### 2019-12-02 — Second breakage of Go syntax since IDE versions 2019.3.x

The second case is documented in #108 where the syntax highlighting of some Go elements were wrong again after updating to IntelliJ version _2019.3.0_. A [comparison of the changes between Nord plugin version 0.8.0 and the time the issue was created (2019-12-02)][comp-time-v0.6.0-v0.7.0][comp-time-v0.8.0-2019-12-02] shows again that there were no changes to the editor color scheme related to the highlighting of Go code.

An **interesting observation** was that the **wrong highlighting could be fixed by disabling and enabling the Nord plugin again without restarting the IDE** (deny/postpone to later when the question dialog shows up).

Again, the “fixes“ were then released in a the new plugin [version 0.9.0][rl-v0.9.0].

### 2020-01-28 — Another breakage of JavaScript & TypeScript syntax in IDE versions 2019.3.x

On 2020-01-28 a new issue has been created that describes the breakage of the syntax highlighting for JavaScript as well as TypeScript (which inherits values from the JavaScript editor scheme keys) in #115. This is **really strange** since the [affected elements were fixed in #78][gh-78-js-changes] to **mitigate the first breakage**!
To fix the problem again, the [color definitions were then defined explicitly in #116][gh-116-js-changes] **instead of relying on the non-working inheritance of other theme keys**.

The [comparison of the changes between Nord plugin version 0.9.0 and the time the issue was created (2020-01-28)][comp-time-v0.9.0-2020-01-28] again showing that there were **no changes to the highlighting of JavaScript or TypeScript syntax elements in the editor color scheme**.

It was also **possible again to temporarily work around the problem by re-enabling or even re-installing the plugin**. This definitely shows that the root cause must be somewhere in the way the IDE loads themes and how editor color scheme keys are inherited from other keys.

Again, the “fixes“ were then released in a the new plugin version [version 0.10.0][rl-v0.10.0] **on 2020-02-11**.

### 2020-02-11 — Now PHP and general _markup_ languages are also broken…

The **latest case occurred only several hours after** [Nord plugin version 0.10.0][rl-v0.10.0] was deployed and made public through the _JetBrains Plugin Marketplace_. This time the highlighting of strings and comments in PHP, Markdown font styles (bold & italic) as well as other elements of _markup_ languages are broken.

Again, a [comparison of the changes between Nord plugin version 0.9.0 and 0.10.0][comp-v0.9.0-v0.10.0] shows that there no changes to the highlighting for editor color scheme keys for PHP, Markdown or any _markup_ languages or “Language Default“ styles.

**During the testing of Nord plugin version 0.10.0**, that was **released to fix the problems of the broken JavaScript & TypeScript highlighting**, there were **no problems regarding _markup_ styles** and all elements were working fine in Markdown files. Right after deploying the plugin to the _JetBrains Plugin Marketplace_, the **highlighting suddenly broke “out of nowhere“ after updating the plugin for my IntelliJ**.

## Conclusion

These random breakages “drive me nuts“ and it's **frustrating as a theme author to no being able to track down the root cause**. Since the **problem occurs randomly**, but **can also be temporarily mitigated through one or more plugin re-activation or re-installations**, the **problem origin must be a bug in the IDE itself**.

## Next Steps

1. **Implement workaround for other possible breakages** — To prevent more styles from breaking, I'll replace all editor color scheme keys that inherit values from other keys with the explicit style definitions instead. This causes the code of the editor scheme to increase drastically due to duplicate and repeated styles, but it currently the only way to work around this non-working style inheritance in the IDE theme API.
2. **Submit a bug report to the JetBrains IntelliJ bug tracker** — In order to get rid of this annoying bug, I'll submit a detailed bug report to the JetBrains bug tracker for the IntelliJ IDE including the details of this issue.

## Feedback Always Welcome!

If you're also affected by this problem, I'll really appreciate every feedback so this can be used to find the root cause and fix this bug permanently :rocket:

[comp-time-v0.6.0-v0.7.0]: https://github.com/arcticicestudio/nord-jetbrains/compare/master@%7B2019-05-23%7D...master@%7B2019-07-16%7D
[comp-time-v0.8.0-2019-12-02]: https://github.com/arcticicestudio/nord-jetbrains/compare/v0.8.0...develop@%7B2019-12-02%7D
[comp-time-v0.9.0-2020-01-28]: https://github.com/arcticicestudio/nord-jetbrains/compare/v0.9.0...develop@%7B2020-01-28%7D
[comp-v0.9.0-v0.10.0]: https://github.com/arcticicestudio/nord-jetbrains/compare/v0.9.0...v0.10.0
[gh-116-js-changes]: https://github.com/arcticicestudio/nord-jetbrains/pull/116/files#diff-1146aace8d65c51b72c60139418ad4d0R1118-R1133
[gh-78-js-changes]: https://github.com/arcticicestudio/nord-jetbrains/pull/78/files#diff-1146aace8d65c51b72c60139418ad4d0R1016-R1018
[rl-2019-2]: https://www.jetbrains.com/idea/whatsnew/#v2019-2-editor
[rl-v0.10.0]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.10.0
[rl-v0.8.0]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.0
[rl-v0.9.0]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.9.0
[tm]: https://macromates.com

**Comment by Tom1206** [comment]
I have also encountered a few scheme bugs since the 0.10 update.
The first one is with all colors (hex, name, variables, ...) on CSS (and SCSS, ...) files. They have a brownish color, as shown in the screenshot :

![Annotation 2020-02-13 094441](https://user-images.githubusercontent.com/10849079/74417080-6e188780-4e46-11ea-8673-dd2de85b4e26.png)

I can't fix it with the color scheme settings unfortunately :

![Annotation 2020-02-13 094522](https://user-images.githubusercontent.com/10849079/74417211-a324da00-4e46-11ea-8540-abb37d77b745.png)

I fear that the "unused" attribute `parent_scheme` wasn't so unused after all, because there is a few other things broken (I will report). It seemed to fix fine a few badly inherited colors, but introduced random brownish elements here and there.

**Comment by Tom1206** [comment]
The active tab is now the wrong color, somehow...

![image](https://user-images.githubusercontent.com/10849079/74418986-88079980-4e49-11ea-8ad7-a9eca1385d2b.png)

Easily fixed in the settings :

![image](https://user-images.githubusercontent.com/10849079/74419123-b71e0b00-4e49-11ea-92b8-7e1dfffc06e5.png)

![image](https://user-images.githubusercontent.com/10849079/74419276-f2b8d500-4e49-11ea-92a9-61f342423dd2.png)

![image](https://user-images.githubusercontent.com/10849079/74419347-09f7c280-4e4a-11ea-9fcd-c54c872f847c.png)

**Comment by Tom1206** [comment]
The Diff & Merge folded code is the wrong color on 0.10:

![image](https://user-images.githubusercontent.com/10849079/74420790-49bfa980-4e4c-11ea-9882-6da48a4cc9d7.png)

Easily fixed by adding a color to the background:

![image](https://user-images.githubusercontent.com/10849079/74420860-68be3b80-4e4c-11ea-980b-3e8d7d976213.png)

**Comment by yuru7** [comment]
I have the same appearance.

The following capture is "pom.xml" of Maven.
Some are normal, some are broken (brown text color).

After reinstalling Nord v0.9, the problem was fixed.

![image](https://user-images.githubusercontent.com/13458509/74474145-3cf09380-4ee8-11ea-90ca-c1c1b579fcda.png)

**Comment by Tom1206** [comment]
There is a problem with function parameters in Typescript.

<img width="633" alt="Screenshot 2020-02-13 at 22 35 56" src="https://user-images.githubusercontent.com/10849079/74480450-34c93180-4eb1-11ea-9469-bf7536501b79.png">

**Comment by arcticicestudio** [comment]
Thanks @Tom1206 and @yuru7 for your feedback 💪 

As a first mitigation step towards the "random" color breakage, I've implemented and submitted the change to replace all inherited colors with their explicit definitions in #121. The only small quirk of the change is the increased amount of definitions, but I've checked other builtin and community themes and most of them don't make use of inherited colors (no `baseAttributes` set). A advantage of this change is that there's now "less magic": Instead of relying on the default color inheritance, every theme key for a syntax is now within the color scheme file making it way easier to find and modify them.

There's also another factor that might be reason for the wrong colors both of you found: The [latest IDE versions 2019.3.3 have been released at the same day][jbb] like the Nord plugin version 0.10.0 🙃
I've quickly checked the changes and it looks like they've also introduced some changes to editor color schemes as well as new keys that affect the UI, e.g. there are new `TAB_*` editor scheme keys which might  explain the behavior @Tom1206 found.

Next steps to fix the problems both of you found and going through the color scheme keys again and afterwards to add support for new or changed keys. I'll try to forge a new [plugin version 0.11.0][v] over the weekend.

[jbb]: https://blog.jetbrains.com/idea/2020/02/intellij-idea-2019-3-3-is-out
[v]: https://github.com/arcticicestudio/nord-jetbrains/milestone/12

**Comment by Tom1206** [comment]
There is a few other brownish colours here and there:

<img width="892" alt="Screenshot 2020-02-15 at 12 04 44" src="https://user-images.githubusercontent.com/10849079/74586807-a4433c00-4feb-11ea-8061-e3512c0df4e4.png">

<img width="892" alt="Screenshot 2020-02-15 at 12 04 35" src="https://user-images.githubusercontent.com/10849079/74586812-a5746900-4feb-11ea-91fd-7f3a8aac18fd.png">

<img width="892" alt="Screenshot 2020-02-15 at 12 04 22" src="https://user-images.githubusercontent.com/10849079/74586811-a5746900-4feb-11ea-9e2f-655154cda6e2.png">

This one is quite common in C#
<img width="892" alt="Screenshot 2020-02-15 at 12 03 22" src="https://user-images.githubusercontent.com/10849079/74586813-a5746900-4feb-11ea-87de-6ae0ad1682c5.png">

<img width="892" alt="Screenshot 2020-02-15 at 12 03 45" src="https://user-images.githubusercontent.com/10849079/74586814-a60cff80-4feb-11ea-8df9-133b545980fc.png">


I just wanna say, thank you @arcticicestudio for all your work this last few days, it's amazing to see how much you care about the quality of Nord, and how much you communicate about it.

**Comment by arcticicestudio** [comment]
Thanks for all the feedback :blue_heart: 
The actual fix for all these broken colors was indeed the removed `parent_scheme` attribute. This is so strange that it is required to add this, otherwise many of the defined colors of a theme are simply ignored. I've written down some more details in #129 and reverted the change in #137.
I'll release and deploy plugin version 0.11.0 to the marketplace this evening which also [includes some other new features][m].

---

Closed by #129, #137

[m]: https://github.com/arcticicestudio/nord-jetbrains/milestone/12?closed=1
