### ISSUE TITLE
Pink line between editor and breadcrumbs in 0.11.0

### ISSUE THREAD

**Issue by Tom1206** [arcticicestudio/nord-jetbrains#138]
Probably linked to #125 ?

<img width="906" alt="Screenshot 2020-02-15 at 23 21 35" src="https://user-images.githubusercontent.com/10849079/74596066-5b6ea000-504a-11ea-847e-a2811be2875d.png">

**Comment by Tom1206** [comment]
It appears on WebStorm and PHPStorm, even after full plugin reinstallation and ide restart

**Comment by arcticicestudio** [comment]
Thanks again for the report @Tom1206 :+1: 
Looks like I've missed to adjust the "test color" before submitting #136 that I use to quickly identify UI and syntax elements that are affected by a specific theme color key :unamused:

**Comment by arcticicestudio** [comment]
Released and deployed to the marketplace in version [0.11.1][] :rocket:  

[0.11.1]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.11.1
