### ISSUE TITLE
Colours on node modules folder in the project explorer are unreadable.

### ISSUE THREAD

**Issue by gochev** [arcticicestudio/nord-jetbrains#143]
The color on node modules folder and everything bellow it is completely unreadable.
This is a dealbreaker to use this theme for javascript development, also I was not able to find a way to change it.

<img width="420" alt="Screen Shot 2020-02-21 at 11 51 07" src="https://user-images.githubusercontent.com/5537142/75023497-920c4680-54a0-11ea-9ce3-3a655734529f.png">
<img width="309" alt="Screen Shot 2020-02-21 at 11 51 12" src="https://user-images.githubusercontent.com/5537142/75023501-933d7380-54a0-11ea-83e1-8a36ed216c1a.png">

The hidden folders are not that great as well, but at least are visible in completely dark room.

<img width="294" alt="Screen Shot 2020-02-21 at 11 51 44" src="https://user-images.githubusercontent.com/5537142/75023506-959fcd80-54a0-11ea-94b7-8c797715850b.png">

**Comment by gochev** [comment]
thats bad but I found it is a duplicate of https://github.com/arcticicestudio/nord-jetbrains/issues/112

**Comment by arcticicestudio** [comment]
Duplicates #57 and #67

---

Hi @gochev :wave:, thanks for your contribution :+1:
This is the same problem described in #67, [please see my comment][c] and the follow-up conversation that provides information about the problem and **how to solve it on your side**.

As a theme author there is currently no way to fix this using the IDE's theme API and it might need to be resolved by JetBrains. There is an idea how this could be fixed posed by a user in https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-526185576, but it still need to be evaluated and tested.

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/67#issuecomment-511395276
