### ISSUE TITLE
Nord Theme invalid in PyCharm

### ISSUE THREAD

**Issue by abraaocrvlho** [arcticicestudio/nord-jetbrains#144]
Hello good afternoon.
I try to install the nord theme on my PyCharm, but it says it is "an invalid theme", how can I solve this?

**Comment by arcticicestudio** [comment]
Hi @abraaocrvlho 👋 
Have you followed the [install instructions from the official Nord documentation][d]? 

[d]: https://www.nordtheme.com/docs/ports/jetbrains/installation

**Comment by abraaocrvlho** [comment]
> Hi @abraaocrvlho 👋
> Have you followed the [install instructions from the official Nord documentation](https://www.nordtheme.com/docs/ports/jetbrains/installation)?

Yes, I followed the instructions described on the website, I download the .jar file and go to settings> import theme.
But unfortunately the error.

**Comment by abraaocrvlho** [comment]
![image](https://user-images.githubusercontent.com/28541789/75984675-9afe0e80-5ec9-11ea-831f-a25ae55b93e7.png)

**Comment by abraaocrvlho** [comment]
> Hi @abraaocrvlho 👋
> Have you followed the [install instructions from the official Nord documentation](https://www.nordtheme.com/docs/ports/jetbrains/installation)?


Hello, forgive me, I was trying to install it in a different way, importing the theme, that's why the error. Sorry to waste your time. I will close the issue.

**Comment by arcticicestudio** [comment]
No problem, great to see it works for you now :rocket:
