### ISSUE TITLE
idea git .....

### ISSUE THREAD

**Issue by time-byte** [arcticicestudio/nord-jetbrains#148]
![image](https://user-images.githubusercontent.com/40427877/79125850-6ab36500-7dd1-11ea-838e-a4f709d29880.png)

**Comment by arcticicestudio** [comment]
Hi @time-byte :wave:, thanks for your contribution :+1:

Could you please explain in details what's the reason for this issue especially if there are highlighting errors or just some understanding problems regarding the gutter stripes.

**Comment by time-byte** [comment]
I can not speak English. The following is machine translation. 

It was used before nord

![image](https://user-images.githubusercontent.com/40427877/79202017-8b2ffd80-7e6b-11ea-8edb-c0dcf74353dd.png)

**Comment by time-byte** [comment]
vacode  The binding line is beautiful
![image](https://user-images.githubusercontent.com/40427877/79203080-178ef000-7e6d-11ea-9b7d-10cee3291354.png)

**Comment by zmirc** [comment]
Beautiful and more discrete. It's too bulky currently.

**Comment by arcticicestudio** [comment]
@zmirc Thanks for helping out here 👍 
The width of the bar can not be modified by theme authors but is “hardcoded“ in IntelliJ. I guess the width is calculated automatically based on the available space or resolution to ensure it doesn't take too much space.

As a theme author only the actual color can be customized and even when the “Error stripe mark“ option would not be disabled it would only allow to select options to e.g. underline an error.

<div align="center"><img src="https://user-images.githubusercontent.com/7836623/80452498-b3693300-8926-11ea-8622-98ee7edd41bd.png" /></div>

As an example here are the themes can are bundled with IntelliJ by default that use the same bar width with different colors:

<p align="center"><strong>Darcula</strong> theme</p>
<div align="center"><img src="https://user-images.githubusercontent.com/7836623/80452494-b19f6f80-8926-11ea-80c2-e08be3c7066b.png" /></div>

<p align="center"><strong>macOS Light</strong> theme</p>
<div align="center"><img src="https://user-images.githubusercontent.com/7836623/80452504-b49a6000-8926-11ea-9928-93713a97cb72.png" /></div>

@time-byte If you'd like to disable the gutter bars at all you can do so in the **Editor** → **General** preferences in the **Gutter** section.

<div align="center"><img src="https://user-images.githubusercontent.com/7836623/80452501-b401c980-8926-11ea-985f-2ece79fd819d.png" /></div>

Going to close this issue for now, but feel free to reopen if this doesn't answer your question.
