### ISSUE TITLE
hard to see - almost invisible - git ignored files

### ISSUE THREAD

**Issue by zmirc** [arcticicestudio/nord-jetbrains#149]
![image](https://user-images.githubusercontent.com/1527236/79560525-0aaa1080-80a8-11ea-8800-073c5ebe5c33.png)
Git ignored files are hard to see, almost invisible.
See example in this JS project. Example in Intellij 2020.01: 
"node_modules" can't be read and it's not even selected selected. (1st img)
Similar for ".idea", though it's slightly better because it doesn't have the different background as "node_modules" folder has.
If I click on it, it can be read (2nd img)
![image](https://user-images.githubusercontent.com/1527236/79560679-4f35ac00-80a8-11ea-8116-022b91b9fbc5.png)
BTW, thanks a lot for this theme.

**Comment by arcticicestudio** [comment]
Hi @zmirc :wave:, thanks for your contribution :+1:
