### ISSUE TITLE
Wrong variable color in PHPStorm

### ISSUE THREAD

**Issue by mariojackson** [arcticicestudio/nord-jetbrains#151]
Hi Sven!

It seems like the default color for a variable in PHP differs from other languages.

The color in the picture seen below is most probably the default color of Jetbrains its own Darcula theme. 

<img width="353" alt="Screenshot 2020-04-24 at 13 50 25" src="https://user-images.githubusercontent.com/57389555/80210233-b79a0580-8633-11ea-8e0f-01809df263cd.png">

I just made a fresh installation of the current PHPStorm 2020.1 along with the Nord plugin today.

It seems that by default the inheritance in PHP for variables is disabled. When enabling manually or just enabling and then disabling again, the color for the variable correctly turns to white and stays like that.

Edit:
This is also true for constants and parameters.

**Comment by arcticicestudio** [comment]
Hi Mario :wave:, thanks again for another contribution :+1:

Looks like this is also related to #120 (#121) again. The theme must be changed to use explicit color definitions instead of relaying on color inheritances for languages that are especially bundled with PhpStorm. I'll quickly install a trial version and check which syntax highlighting plugins require additional support.

**Comment by arcticicestudio** [comment]
I've submitted #153, let me know if there are styles you might think that can be improved. Since I've never used PHP it's possible that if "misinterpreted" some of the syntax elements, e.g. I'm not sure if the `Query(...)` on lines 38-40 are _constructors_ or _class instantiators_. Also on line 37 there's `$$def` which the syntax plugin calls a "Variable variable" and on line 35 a "magic" attribute (some kind of special class field?).

<div align="center"><img src="https://user-images.githubusercontent.com/7836623/80377419-8e7bae00-889b-11ea-8c84-a8b569242920.png" /></div>

**Comment by mariojackson** [comment]
You always inspire me with your quality of work, great documentation and thoughtfulness. I already started to make better git messages myself since reading yours, by including a title and description instead of writing only a short one-liner :).

I'm also not working that often with PHP nowadays but the above picture does look good to me. The colors are adjusted to be similar like in Go for example. 

- The `new Query(...)` part is the call of a constructor
- Line 37 is a variable variable name. I think it's whether confusing and only saw it very seldom in real projects - and where I saw them were pretty old ones. You can basically change the name of a variable dynamically. 
- Line 35: Magic methods are methods which are pre-occupied by PHP like `__toString()`

**Comment by arcticicestudio** [comment]
Thanks for the compliments 😊 
I see it that way, the history and changes of a _Git_ repository should tell the project's story and should also be the main persistence layer for it. The probability is very low for GitHub (and that would also be a disaster), but when there are some problems with the database and issues/PRs are lost, some parts of the story of a project are also gone. There have been many projects, including really large and popular ones, whose repositor(y/ies) were suddenly gone (reasons like argues between maintainers, too much stress etc.) and so all documentation through issues/PRs was gone (when GitHub popup warns before deleting a repository they really mean it that way regarding the "permanent data loss" section). Writing the project's change reasons right into commits ensures the story is safe: even if you deleted your local repository, someone else has a clone of it like e.g. in my case a simple service running on my private servers that mirrors repositories.
Only part I miss is a way to include data like images in commits (base64 might kill it 😄) without the need to commit them right into the repository. Also if you like the idea maybe you like to check out MichaelMure/git-bug, a fantastic project of an “Distributed, offline-first bug tracker embedded in Git, with bridges“ (written in Go 💙)

Anyway, drifted away from the topic again 😃 
I'll merge the PR and review some other PRs and issues that might also be included in the next release version before deploying it to the _JetBrains_ plugin registry.
Thanks again for your feedback, also learned something about PHP again (tried their docs, but in my opinion they need a full refactor).

**Comment by mariojackson** [comment]
Thank you for the `git-bug` suggestion, it seems pretty interesting and since it has a terminal UI and I'm a terminal guy and since it's written in Go, it seems even more interesting to me. Will definitely check it out :).

**Comment by arcticicestudio** [comment]
@mariojackson The change is now available in the freshly shipped [version 0.12.0](https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.12.0) that is also shipped to the _JetBrains Plugin Registry_. The update is currently processed and should be available within the next 24h from [Nord's plugin page](https://plugins.jetbrains.com/plugin/10321-nord).

**Comment by mariojackson** [comment]
Nice! Thank you Sven!
