### ISSUE TITLE
Unable to view folders due to color scheme problems

### ISSUE THREAD

**Issue by rdandnayak** [arcticicestudio/nord-jetbrains#155]
This is Angular Project.

i am unable to see few folders properly, dist/ node_modules/

![image](https://user-images.githubusercontent.com/816239/81469867-1bf8bf80-9205-11ea-8903-3a76be099567.png)

**Comment by arcticicestudio** [comment]
Duplicates #57 

---

Hi @rdandnayak :wave:, thanks for your contribution :+1:
This is a known problem tracked in the pinned issue #57. Please see [my comment that describes the current limitation for theme authors][c] as well as comments from other users like the ones that describes [how to fix it on your side][c2].

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-517267937
[c2]: https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-549154675
