### ISSUE TITLE
Font used in UI

### ISSUE THREAD

**Issue by marcorieser** [arcticicestudio/nord-jetbrains#163]
I am curious which font is used in the screenshots for the UI. Sadly the dropdown overlaps the font name but it ends with "Text". 
<img width="1072" alt="ui-settings-appearance-1" src="https://user-images.githubusercontent.com/2395800/95993483-77bc1a00-0e2f-11eb-9eb9-16adc984441a.png">
Does someone knows / remembers its name?

**Comment by arcticicestudio** [comment]
Hi @marcorieser, it is detected by most applications as `.SF NS Text` which stands for Apple‘s main system font family called [San Francisco][sf]. Unfortunately it is closed source, but you can simply create an Apple account and download it from their developer resource page.

I try to take screenshots like this on my _macOS_ system to achieve the most “crisp“ font and UI rendering. Their rendering engine is (unfortunately) still unbeaten compared to most open source implementations and results in beautiful screenshots in combination with this typeface.
My other systems are running _Arch Linux_ (server & desktop) with _GNOME_ and _AwesomeWM_ (desktop only) and if you're looking for an fantastic UI font family I can absolutely recommend [Inter UI][i] that is [open source][ir].

[sf]: https://developer.apple.com/fonts
[i]: https://rsms.me/inter
[ir]: https://github.com/rsms/inter

**Comment by marcorieser** [comment]
@arcticicestudio Thank you very much.
