### ISSUE TITLE
Git ignored files not readable

### ISSUE THREAD

**Issue by eliorc** [arcticicestudio/nord-jetbrains#170]
When placing files under `.gitignore` they become unreadable when using the Nord theme.

Attaching screenshot:
![image](https://user-images.githubusercontent.com/17727283/100203525-658fca00-2f0b-11eb-9f3c-46d39975908c.png)

**Comment by arcticicestudio** [comment]
Duplicates #57

---

Hi @eliorc 👋🏼 , thanks for your contribution 👍🏼 

This is already a known problem that is tracked in #57, please subscribe to this issue for more details and updates.
