### ISSUE TITLE
PyCharm Constrast Issue

### ISSUE THREAD

**Issue by napsterv** [arcticicestudio/nord-jetbrains#171]
![Screenshot 2020-12-11 181626](https://user-images.githubusercontent.com/8555852/101905622-bf67e380-3bdd-11eb-96e5-ed6f701479d6.png)

It's hard to read what's written after the word Scope (highlighted in Yellow)

**Comment by arcticicestudio** [comment]
Hi @napsterv 👋🏼 , thanks for your contribution 👍🏼 

Can you please try the workarounds described in #57, it looks like this UI element is also not customizable by a theme but uses user-side configurations instead.

**Comment by napsterv** [comment]
@arcticicestudio Okay, I will try and get back to you.😃

**Comment by napsterv** [comment]
@arcticicestudio I did what was suggested in https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-549154675 and PyCharm removed the scope keyword and it appears fine now, Image below.

![image](https://user-images.githubusercontent.com/8555852/102765025-102bc900-43a2-11eb-8cc7-156d3d9f95ec.png)

The _scope_ keyword is not too important for me as the size of my project is small. However, I think for bigger projects and teams it might be important. But as you said it's not customizable by a theme but uses user-side configurations instead maybe we wait for JetBrains to figure this out.
