### ISSUE TITLE
CLion support not working?

### ISSUE THREAD

**Issue by Bobbbay** [arcticicestudio/nord-jetbrains#173]
Hey y'all! Just grabbed Nord on my beloved CLion. Sadly, seems like my whole editor isn't Nordified :(.

![image](https://user-images.githubusercontent.com/49123594/111541618-18986380-8747-11eb-9e6a-5f2250fbfc1a.png)

Seems fairly strange to me that a JetBrains theme doesn't work on all editors.

Cheers!

**Comment by arcticicestudio** [comment]
Hi @Bobbbay :wave:

Which Nord plugin version do you have installed?
Did you [activate the UI theme][d] in the preferences after the installation?

[d]: https://www.nordtheme.com/docs/ports/jetbrains/installation#ui-theme

**Comment by Bobbbay** [comment]
Hi Team 👋🏼 

I feel so stupid 😅. I activated it in Color Scheme but not in Appearance, haha.

As a side question, should `target` or `cmake-build-debug` look like this?

![image](https://user-images.githubusercontent.com/49123594/111782044-f0b41780-888e-11eb-837c-9729fc6cca0c.png)

**Comment by arcticicestudio** [comment]
No problem, nice to see it works for you now 👍🏻
The problem regarding the “sub-optima“ highlighting of ignore tree items is still a know problem that is tracked in the pinned issue #57.

**Comment by Bobbbay** [comment]
Perfect, thanks for the awesome "customer" support! 😉
