### ISSUE TITLE
Bad contrast in IntelliJ's target folder

### ISSUE THREAD

**Issue by heliommsfilho** [arcticicestudio/nord-jetbrains#179]
**Issue:**

When I expand the _target_ folder of a Java project, the names of the files and folders inside it becomes illegible due a bad contrast between the font and the background:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/10871439/134821680-7ff72b09-5c93-4e4c-ae8c-1a64ab2bf13f.png">

**System Info:**

- Operating System: MacOS Big Sur 11.6
- IntelliJ version: 2021.2.2 (Build #IU-212.5284.40, built on September 14, 2021)

**Comment by arcticicestudio** [comment]
Duplicates #57

---

Hi @heliommsfilho :wave:

This is already a known problem that is tracked in #57, please subscribe to this issue for more details and updates.
