### ISSUE TITLE
Background of menu items is different to popup window.

### ISSUE THREAD

**Issue by felipearpa** [arcticicestudio/nord-jetbrains#190]
The color of each item of menu is different (is brighter) to the color to the window popup. You must look at in detail the separator in the image

![Screen Shot 2021-10-15 at 2 08 29 PM](https://user-images.githubusercontent.com/25959674/137540439-aa38dcdf-332b-4007-8d44-c6e198ff0b90.png)

Now, I am fixed. How can I contribute?

![Screen Shot 2021-10-15 at 2 09 01 PM](https://user-images.githubusercontent.com/25959674/137543365-88bb4c3f-8052-4b42-975f-7473d5eb3281.png)

Thanks.

**Comment by arcticicestudio** [comment]
Hi @felipearpa :wave:, thanks for your contribution :+1:
Thanks for your patience for a reply, unfortunately I missed your question about how to contribute. An improvement was submitted in #192 and has been merged so the next release version will include the changes.

**Comment by nomenon** [comment]
When next release will be?

**Comment by nomenon** [comment]
any release?

**Comment by dmdt** [comment]
Hi! Is it planned to release this?
