### ISSUE TITLE
No window borders on gnome 41.5

### ISSUE THREAD

**Issue by Mimameid** [arcticicestudio/nord-jetbrains#195]
Edit:

I figured this is related to the default window manager used within' manjaro. Will have to investigate a bit more. Can probably be deleted.

![image](https://user-images.githubusercontent.com/18268210/165032769-53a65733-a421-4be1-85cc-0d2af5562992.png)

**Comment by svengreb** [comment]
Hi @Mimameid :wave:

How is this related to any JetBrains product? This theme is not scoped for terminals but applications from [JetBrains][1] like IDEs. Please add more context about your problem or close this issue if it was opened in the wrong repository or not meant for the Nord project at all.

[1]: https://www.jetbrains.com

**Comment by svengreb** [comment]
Closing since this is not related to this project at all and without further details this can not be processed.
