### ISSUE TITLE
Full editor theming support

### ISSUE THREAD

**Issue by Al2Me6** [arcticicestudio/nord-jetbrains#39]
With the release of Intellij 2019.1 and the [full editor theming](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_intro.html), will a full theme be possible for nord? That would greatly improve the UX.

**Comment by arcticicestudio** [comment]
It's planned to support this for sure :wink: 
I've already started some prototyping after it was available in the beta version some weeks ago, but it needs more time to include all supported UI elements and polish it.

**Comment by arcticicestudio** [comment]
The UI theme has been implemented in version [0.5.0][] 🎉

There are currently problems deploying it to the [JetBrains Plugin Repository][r] so it might be possible that a patch version 0.5.1 might be necessary to finally make it available.

[0.5.0]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.5.0
[r]: https://plugins.jetbrains.com/plugin/10321-nord-color-scheme
