### ISSUE TITLE
Installation from marketplace doesn't work / version is out of date

### ISSUE THREAD

**Issue by rwev** [arcticicestudio/nord-jetbrains#50]
I tried to install the plugin via the plugin marketplace per the directions in the README.md but after doing this, "Nord" wasn't listed as an option in the theme drop-down. 

To solve this issue, I had to go to the [JetBrain Plugins site](https://plugins.jetbrains.com/plugin/10321-nord/versions), download the jar, and "Install Plugin from Disk."

It appears the v0.4.0 was installed by the marketplace, while the .jar I downloaded was v0.5.0.

![image](https://user-images.githubusercontent.com/40538419/57798935-2d4edf00-770b-11e9-9312-a3a50bc27336.png)

IntelliJ Idea 2019.1.2 (Ultimate Edition) Build #UI-191.7141.44

**Comment by arcticicestudio** [comment]
Users with currently installed versions less or equal to `0.4.0` must reinstall the plugin.
As of version `0.5.0` the plugin XML ID changed to better fit the package hierarchy naming scheme. This means plugin versions less or equal to `0.4.0` (old ID) won't receive updates automatically.

Please see the [official installation & setup documentation][d] for more details and a guide how to migrate.

[d]: https://www.nordtheme.com/docs/ports/jetbrains/installation
