### ISSUE TITLE
Background color and text in tip "Gradle files have changed ..." are similar

### ISSUE THREAD

**Issue by singlepig** [arcticicestudio/nord-jetbrains#52]
![](https://i.loli.net/2019/05/20/5ce21bb15a51044333.png)

I can't see words in this tip clearly. It might be better to change the background color.

**Comment by singlepig** [comment]
Background color value is d8dee9

**Comment by arcticicestudio** [comment]
Hi @singlepig, thanks for your report 👍 
I've also noticed these banners, but I haven't found any theme key that where I can change it's color.
I'll take another look in the course of the week and maybe create a requests in JetBrains bugtracker to allow to style these UI component.

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/59386106-bc571300-8d1a-11e9-86e7-45841f0e5aea.png)

Same problem

**Comment by arcticicestudio** [comment]
I've found the responsible theme key: `NOTIFICATION_BACKGROUND`

It's defined in the editor color scheme and not in the new UI theme :smile: 
I guess JetBrains will move these sooner or later to the UI theme (makes sense for a UI element like this), but for now it's changed in #61 to make the text readable again.

Take a look at #61 if you like to get more details and maybe check out the branch to test the change.
It will be merged and deployed with the next release version.
