### ISSUE TITLE
Block selection in IdeaVim is unusable due to low contrast

### ISSUE THREAD

**Issue by j1ah0ng** [arcticicestudio/nord-jetbrains#58]
In Normal IdeaVim mode, the entire line a cursor is on is highlighted as follows:
![image](https://user-images.githubusercontent.com/13944989/58816951-6ded9a00-85df-11e9-8f04-545c6a91ba3b.png)

Entering block selection mode using Ctrl+V and attempting to select text is difficult since the highlighted/selected text colour is very similar to the colour that the entire line is highlighted with:
![image](https://user-images.githubusercontent.com/13944989/58817016-96759400-85df-11e9-953d-c88262d2f13c.png)
In this example, the two `protected` key words have been selected. 

The situation is worse if the block selection is only one one line, as it's very difficult to tell where the selection begins:
![image](https://user-images.githubusercontent.com/13944989/58817051-aee5ae80-85df-11e9-9b16-534148a19ea7.png)
In this example, the type `long` has been selected, but this is difficult to see due to the low contrast.

**Comment by arcticicestudio** [comment]
Hi @sushisharkjl :wave:, thanks for your contribution :+1:

This is a known visual problem also reported in #55 and [I've submitted a feature request in Jetbrains ticket system][t] that should help to fix such problems and improve selection at all.

[t]: https://youtrack.jetbrains.com/issue/IDEA-215064

**Comment by svengreb** [comment]
@j1ah0ng Thanks for your patience, there are tons of tasks in the Nord project and my free time is limited to work on the massive amount of issues/PRs.
Anyway, I close this issue in favor of #55 so please subscribe to this issue for further updates and discussions.
