### ISSUE TITLE
New Windows titlebar in EAP has two different colors 

### ISSUE THREAD

**Issue by sfrench87** [arcticicestudio/nord-jetbrains#65]
![titlebar](https://user-images.githubusercontent.com/48254143/59553275-c54e1b80-8f8a-11e9-9f57-fdbc32ddf4de.jpg)

A slightly lighter blue is showing under file, edit, view etc, different to the rest of the titlebar.

**Comment by arcticicestudio** [comment]
Hi @sfrench87 :wave:, thanks for your contribution :+1:
I guess you're running on Linux or Windows so this is related to the [`Menu.background`][k] UI theme key. It seems like IntelliJ does not distinguish between the unfocused state and when a menu is opened. There is no theme key to explicitly set the background color for unfocused state so this need to be resolved in IntelliJ's UI theme API.
Would be nice if you can open a request in [JetBrains YouTrack][jyt] (bugtracker) so maybe this can be implemented in IntelliJ.

[k]: https://github.com/arcticicestudio/nord-jetbrains/blob/develop/src/nord.theme.json#L160
[jyt]: https://youtrack.jetbrains.net

**Comment by sfrench87** [comment]
Submitted issue here [WEB-39475](https://youtrack.jetbrains.com/issue/WEB-39475).

**Comment by sfrench87** [comment]
Just wanted to update the fault and say the issue has been marked as fixed but i'm not exactly sure what they have done.

**Comment by arcticicestudio** [comment]
Thanks for the update, have you been able to verify that the fix is working? I guess you need to update to the latest IntelliJ version 2019.2 as well as to the Nord plugin version [0.8.1][] to make sure the latest bug fixes are included.

[0.8.1]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.1

**Comment by sfrench87** [comment]
Sorry for not replying sooner, it seems be using the same colour for the whole title bar now.

![Annotation 2019-10-10 124233](https://user-images.githubusercontent.com/48254143/66565947-9f610e00-eb5b-11e9-861c-d765723fc923.jpg)

**Comment by arcticicestudio** [comment]
It the problem this occurring with the latest WebStorm release version? There have been some fixes regarding the window theming on different operating systems in the latest versions.
If it has been fixed please close this issue.
