### ISSUE TITLE
Low contrast on tabs for active excluded and untracked files

### ISSUE THREAD

**Issue by lppedd** [arcticicestudio/nord-jetbrains#68]
See image below.
The first on the left is an external file, the second is a new - untracked file.
Both active.

![image](https://user-images.githubusercontent.com/19871649/61593175-6bb9bc00-abdc-11e9-9a69-59352f406e04.png)

**Comment by arcticicestudio** [comment]
Hi @lppedd, this is the same problem described in #67, [please see my comment][c] that provides information about the problem and how to solve it on your side. As a theme author there is actually no way to fix this and it must be resolved within the Jetbrains theme API itself.

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/67#issuecomment-511395276

**Comment by lppedd** [comment]
@arcticicestudio Thanks. I had read it but I thought it was another issue.
I've removed all the custom colors but it's actually worse than before.

**Comment by arcticicestudio** [comment]
I guess to remove the background highlighting at all the _File Colors_ settings must be disabled completely. There's a small checkbox at the top of the _File Colors_ settings view where you can decide the element types of the IDE the color should apply to. Even when you remove all custom colors the IDE will fall back to "hardcoded" defaults values.
