### ISSUE TITLE
Code completion selection background is inconsistent

### ISSUE THREAD

**Issue by cjkent** [arcticicestudio/nord-jetbrains#94]
The background colour of the selected item in the code completion popup is different depending on how the pop was triggered.

If the popup is triggered manually (by pressing ctrl+space) then the background of the selected item is lighter than the other items.

![image](https://user-images.githubusercontent.com/98477/62782241-ba5ac780-bab1-11e9-9c64-3f377cf4758d.png)

If the popup is triggered automatically as you're typing then the background of the selected item is darker than the other items (check the option "show suggestions as you type" to see this behaviour).

![image](https://user-images.githubusercontent.com/98477/62782330-f2620a80-bab1-11e9-801f-e25c955eb072.png)

Having the selected item darker in one case and lighter in the other is very confusing.

Also the background of the selected item is too similar to the other items in both cases. It would be easier to see which item is selected if there was a bigger difference between the background colours.

**Comment by cjkent** [comment]
In the second case, the background colour changes from dark to light when the selection changes.

**Comment by arcticicestudio** [comment]
Hi @cjkent :wave:, thanks for your contribution :+1:
Sorry for the delay, life keeps me busy.

Is the problem the same like described in #95? If so, a fiy has been submitted in #118 that'll be included in the [next release version 0.10.0][v].

[v]: https://github.com/arcticicestudio/nord-jetbrains/projects/14

**Comment by cjkent** [comment]
>Sorry for the delay, life keeps me busy.
Don't apologise, thanks for the beautiful theme!

It's very similar, but it's not quite the same problem. In #95 the background for the selected item is missing (or is the same as unselected items) when the completion popup appears automatically.

The problem I see is that the background of the selected item is darker than unselected items when the popup appears automatically, and it is lighter than the background of unselected items when you press ctrl-space.

It seems possible that the underlying cause is the same and my problem will be fixed in 0.10.0.

If the problem is still there in 0.10.0 I'll comment again on this issue.

**Comment by cjkent** [comment]
It's fixed in 0.10.0.

Thanks again for a great theme.
