### ISSUE TITLE
Selection background in code competition

### ISSUE THREAD

**Issue by alekc** [arcticicestudio/nord-jetbrains#95]
Possibly related to https://github.com/arcticicestudio/nord-jetbrains/issues/88 and https://github.com/arcticicestudio/nord-jetbrains/issues/94

0.8.1 version fixed the issue with global background (thx again for that), but there is one small issue: when the code competition is triggered automatically, first selected item misses it's background which will not appear until a key up/down is pressed. If the window is triggered by ctrl-space, then everything works as it should

![bug](https://user-images.githubusercontent.com/302807/62834365-d477df80-bc42-11e9-9225-430c084b2280.gif)

As with  https://github.com/arcticicestudio/nord-jetbrains/issues/88 product affected is GoLang (have not tried with another IDE) on windows 10. Nord version is 0.8.1 (installed manually from release page)

**Comment by arcticicestudio** [comment]
Hi @alekc :wave:, thanks for your contribution :+1:
Sorry for the delay, life keeps me busy.

I've found the root cause and submitted #118 to fix it. It'll be included in the [next release version 0.10.0][v].

[v]: https://github.com/arcticicestudio/nord-jetbrains/projects/14

**Comment by arcticicestudio** [comment]
The fix has been merged and released in version [0.10.0][] 🏷 
The new plugin version has been deployed to the J_etBrains Plugin Marketplace_ and should be available within the next 24 hours 🚀  

[0.10.0]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.10.0
