### ISSUE TITLE
Color consistency issue in search all window

### ISSUE THREAD

**Issue by gayanper** [arcticicestudio/nord-jetbrains#97]
Color consistency issue in search all window

![image](https://user-images.githubusercontent.com/7471994/63398240-96b94a80-c3ea-11e9-9cc7-1864c47d7d0b.png)

**Comment by arcticicestudio** [comment]
Hi @gayanper, this is the same problem described in #67, [please see my comment][c] and the follow-up conversation that provides information about the problem and how to solve it on your side. As a theme author there is actually no way to fix this and it must be resolved within the JetBrains theme API itself.

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/67#issuecomment-511395276
